function phonegap(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',lc='.cache.html',$='/',Vb='17D08B13EDB962FE5574A65DFB79741B',Xb='1E59AB942D2D6A8C60080327730778E2',Yb='38E4323BC09285BD966D11808B0A7FB8',Zb='5C9D08F9E52FE114EEC8A4F419D19394',$b='643A7E488A0F3FB3D3204C8CACA97BA8',_b='68656C63896495C2B0E2AE86C70499AE',ac='6BBEB8D1523453AA7B99530CF84EFC42',bc='87B338D9962B8A9B4BDD3ECEAF6AE835',cc='8CB724BA166F8A4A4D5F34AA396C142F',dc='8E1DEA18D63F69C573553E2FBB0AA759',ec='9005F36EA9FD5B375923204369D4C949',fc='9D3579108CA22F828A9F4DF68CFF434D',kc=':',Wb=':1',nb='::',nc='<script defer="defer">phonegap.onInjectionDone(\'phonegap\')<\/script>',gb='<script id="',qb='=',Z='?',gc='AD0E5B1AA64FC33B0D81EF6F0E4D8071',hc='BA655A862E15F207770B6058284B8FF8',sb='Bad handler "',ic='CF41C22B324DEC7753C83221BFF8C395',mc='DOMContentLoaded',jc='F8D2B84B551FA9F4BECE19EDB6545653',ib='SCRIPT',fb='__gwt_marker_phonegap',Bb='android',Db='android_tablet',jb='base',bb='baseUrl',S='begin',Jb='blackberry',R='bootstrap',ab='clear.cache.gif',pb='content',Kb='desktop',X='end',Pb='file://',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Tb='hosted.html?phonegap',wb='iframe',_='img',Eb='ipad',Fb='ipad_retina',Gb='iphone',Hb='ipod',xb="javascript:''",Sb='loadExternalRefs',kb='meta',Ab='mgwt.os',Cb='mobile',Lb='mobile.user.agent',Mb='mobilesafari',zb='moduleRequested',W='moduleStartup',lb='name',Rb='no',Nb='not_mobile',P='phonegap',Ob='phonegap.env',db='phonegap.nocache.js',mb='phonegap::',yb='position:absolute;width:0;height:0;border:none',Ib='retina',cb='script',Ub='selectingPermutation',Q='startup',eb='undefined',Qb='yes';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}phonegap=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1){if(a.indexOf(Cb)!=-1){return Bb}else{return Db}}if(a.indexOf(Eb)!=-1){if(window.devicePixelRatio>=2){return Fb}return Eb}if(a.indexOf(Gb)!=-1||a.indexOf(Hb)!=-1){if(window.devicePixelRatio>=2){return Ib}return Gb}if(a.indexOf(Jb)!=-1){return Jb}return Kb}();return b}};u[Ab]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};v[Lb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1){return Mb}if(a.indexOf(Gb)!=-1){return Mb}if(a.indexOf(Hb)!=-1){return Mb}if(a.indexOf(Eb)!=-1){return Mb}if(a.indexOf(Jb)!=-1){return Nb}return Nb}();return b}};u[Lb]={mobilesafari:0,not_mobile:1};v[Ob]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1||(a.indexOf(Eb)!=-1||(a.indexOf(Hb)!=-1||(a.indexOf(Gb)!=-1||a.indexOf(Jb)!=-1)))){var b=document.location.href;if(b.indexOf(Pb)===0){return Qb}}return Rb}};u[Ob]={no:0,yes:1};phonegap.onScriptLoad=function(){if(H){q=true;B()}};phonegap.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Sb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Tb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Ub});if(!A()){try{F([Ib,Mb,Rb],Vb);F([Ib,Mb,Qb],Vb);F([Ib,Mb,Rb],Vb+Wb);F([Ib,Mb,Qb],Vb+Wb);F([Gb,Nb,Rb],Xb);F([Gb,Nb,Qb],Xb);F([Gb,Nb,Rb],Xb+Wb);F([Gb,Nb,Qb],Xb+Wb);F([Fb,Mb,Rb],Yb);F([Fb,Mb,Qb],Yb);F([Fb,Mb,Rb],Yb+Wb);F([Fb,Mb,Qb],Yb+Wb);F([Kb,Mb,Rb],Zb);F([Kb,Mb,Qb],Zb);F([Kb,Mb,Rb],Zb+Wb);F([Kb,Mb,Qb],Zb+Wb);F([Db,Mb,Rb],$b);F([Db,Mb,Qb],$b);F([Db,Mb,Rb],$b+Wb);F([Db,Mb,Qb],$b+Wb);F([Fb,Nb,Rb],_b);F([Fb,Nb,Qb],_b);F([Fb,Nb,Rb],_b+Wb);F([Fb,Nb,Qb],_b+Wb);F([Kb,Nb,Rb],ac);F([Kb,Nb,Qb],ac);F([Kb,Nb,Rb],ac+Wb);F([Kb,Nb,Qb],ac+Wb);F([Eb,Nb,Rb],bc);F([Eb,Nb,Qb],bc);F([Eb,Nb,Rb],bc+Wb);F([Eb,Nb,Qb],bc+Wb);F([Jb,Mb,Rb],cc);F([Jb,Mb,Qb],cc);F([Jb,Mb,Rb],cc+Wb);F([Jb,Mb,Qb],cc+Wb);F([Db,Nb,Rb],dc);F([Db,Nb,Qb],dc);F([Db,Nb,Rb],dc+Wb);F([Db,Nb,Qb],dc+Wb);F([Jb,Nb,Rb],ec);F([Jb,Nb,Qb],ec);F([Jb,Nb,Rb],ec+Wb);F([Jb,Nb,Qb],ec+Wb);F([Bb,Nb,Rb],fc);F([Bb,Nb,Qb],fc);F([Bb,Nb,Rb],fc+Wb);F([Bb,Nb,Qb],fc+Wb);F([Ib,Nb,Rb],gc);F([Ib,Nb,Qb],gc);F([Ib,Nb,Rb],gc+Wb);F([Ib,Nb,Qb],gc+Wb);F([Bb,Mb,Rb],hc);F([Bb,Mb,Qb],hc);F([Bb,Mb,Rb],hc+Wb);F([Bb,Mb,Qb],hc+Wb);F([Gb,Mb,Rb],ic);F([Gb,Mb,Qb],ic);F([Gb,Mb,Rb],ic+Wb);F([Gb,Mb,Qb],ic+Wb);F([Eb,Mb,Rb],jc);F([Eb,Mb,Qb],jc);F([Eb,Mb,Rb],jc+Wb);F([Eb,Mb,Qb],jc+Wb);J=w[G(Ab)][G(Lb)][G(Ob)];var L=J.indexOf(kc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+lc}catch(a){return}}var M;function N(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(mc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(mc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Sb,millis:(new Date).getTime(),type:S});m.write(nc)}
phonegap();